// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CommonHeader common header
//
// swagger:model CommonHeader
type CommonHeader struct {

	// x aoc request id
	// Required: true
	XAocRequestID *string `json:"x-aoc-request-id"`
}

// Validate validates this common header
func (m *CommonHeader) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateXAocRequestID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CommonHeader) validateXAocRequestID(formats strfmt.Registry) error {

	if err := validate.Required("x-aoc-request-id", "body", m.XAocRequestID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this common header based on context it is used
func (m *CommonHeader) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CommonHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommonHeader) UnmarshalBinary(b []byte) error {
	var res CommonHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
